# Generated by Django 4.2.5 on 2023-09-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BakedGood',
        ),
    ]
