# Generated by Django 4.2.5 on 2023-10-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_project', '0002_rename_book_bakedgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='bakedgood',
            name='ingredients',
            field=models.ManyToManyField(to='example_project.ingredients'),
        ),
    ]
