# Generated by Django 4.2.5 on 2023-11-11 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_project', '0003_ingredients_bakedgood_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakedgood',
            name='baked_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
